//go:build !noasm && arm64

// AUTO-GENERATED BY GOAT -- DO NOT EDIT

package ml

import "unsafe"

//go:noescape
func vmul_const_add_to(a, b, c, n unsafe.Pointer)

//go:noescape
func vmul_const_to(a, b, c, n unsafe.Pointer)

//go:noescape
func vmul_const(a, b, n unsafe.Pointer)

//go:noescape
func vmul_to(a, b, c, n unsafe.Pointer)

//go:noescape
//func vdot(a, b, n, ret unsafe.Pointer)

//go:noescape
func vdot(src0, src1 unsafe.Pointer, ne uint64, dst unsafe.Pointer)
